FROM ubuntu:focal AS homebrew-base

LABEL maintainer="rluckie@cisco.com" \
      kdk=""

RUN apt -y update && \
    apt -y --no-install-recommends install \
        build-essential \
        ca-certificates \
        curl \
        locales \
        file \
        git \
        sudo && \
    apt -y clean && apt -y autoremove && rm -rf /var/lib/apt/lists/*

RUN useradd linuxbrew -m -G root -s /bin/bash \
	&& echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

USER linuxbrew
RUN sudo localedef -i en_US -f UTF-8 en_US.UTF-8 \
    && CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

FROM ciscosso/kdk:1.23.1 AS final
COPY files/etc/profile.d /etc/profile.d

RUN yes | unminimize
COPY --from=homebrew-base /home/linuxbrew /home/linuxbrew
COPY files/brew_bundles /home/linuxbrew/bundles
RUN chmod -R g+w /home/linuxbrew/ \
    && chown -R root:sudo /home/linuxbrew
